#include "math.h"
#include "math_utilities.h"
#include "smart_power_meter_utilities.h"

#include "sys/log.h"

#include "senml-json.h"

#include "cJSON.h" 


/**
 * The aim of this function is to initialize in the proper range the starting values detected by the sensor.
 * @param voltage is the numeric value of the voltage provided to the building
 * @param current_consumed is the numeric value of the current consumed by the building
 * @param current_produced is the numeric value of the current produced by the building
 * @param power_factor is the numeric value of the loads attacched to the building 
 * @param MAX_AMPER_CONSUMABLE is the value of the maximum ampere consumable in the building
 * @param MAX_POWER_ALLOWED is the maximum power allowed to a building 
*/
void initialize_sensor_values(float *voltage, float *current_consumed, float *current_produced, float *power_factor,float *MAX_AMPERE_CONSUMABLE,int MAX_POWER_ALLOWED){
	
	*voltage=random_value_generation(MIN_VOLTAGE_PROVIDED,MAX_VOLTAGE_PROVIDED);
	*current_consumed=0;
	*current_produced=random_value_generation(MIN_AMPERE_PRODUCTED,MAX_AMPERE_PRODUCTED);
	*power_factor=random_value_generation(MIN_POWER_FACTOR,MAX_POWER_FACTOR);
	*MAX_AMPERE_CONSUMABLE=compute_max_ampere_consumable(MAX_POWER_ALLOWED,MIN_VOLTAGE_PROVIDED,MIN_POWER_FACTOR);
}


/**
 * This function is used to compute the current total power of a building (considering production and consumption).
 * @param voltage is the numeric value of the voltage provided to the building
 * @param current_consumed is the numeric value of the current consumed by the building
 * @param current_produced is the numeric value of the current produced by the building
 * @param power_factor is the numeric value of the loads attacched to the building 
*/
float compute_total_instant_power(float voltage, float current_consumed, float current_produced, float power_factor){
	return sqrt(3)*voltage*(current_consumed-current_produced)*power_factor;
}


/**
 * This function is used to compute maximum amout of ampere consumable by the building.
 * @param max_power is the maximum power usable by the building accordingly with the electrical grid provider
 * @param min_voltage is the minimum voltage provided to the building
 * @param current_produced is the numeric value of the current produced by the building
 * @param min_power_factor is the minimum power factor generated by the building depending of how many loads are attacched
*/
float compute_max_ampere_consumable(float max_power, float min_voltage, float min_power_factor){
	return max_power/(sqrt(3)*min_voltage*min_power_factor)+MAX_AMPERE_PRODUCTED;
}

/**
 * This function is used to generate valid sensor data for the smart power meter.
 * @param voltage is the numeric value of the voltage provided to the building
 * @param current_consumed is the numeric value of the current consumed by the building
 * @param current_produced is the numeric value of the current produced by the building
 * @param power_factor is the numeric value of the loads attacched to the building 
 * @param instant_power is the numeric value of the overall power produced/consumed by the building
 * @param nr_loads_attacched represents the number of loads effectively attached to the building
 * @param MAX_AMPERE_CONSUMABLE is the value of the maximum ampere consumable in the building.
*/
void generate_correct_smart_power_meter_values(float *voltage, float *current_consumed, float *current_produced, float *power_factor,float *instant_power, int nr_loads_attacched, float MAX_AMPERE_CONSUMABLE){

  	*voltage=random_value_generation_gradual_variation(MIN_VOLTAGE_PROVIDED,MAX_VOLTAGE_PROVIDED,VAR_VOLTAGE_PROVIDED,*voltage);
	*current_consumed=random_value_generation_gradual_variation(0,MAX_AMPERE_CONSUMABLE,VAR_AMPERE_CONSUMED,STD_AMP_CONSUMPTION*nr_loads_attacched);
	*current_produced=random_value_generation_gradual_variation(MIN_AMPERE_PRODUCTED,MAX_AMPERE_PRODUCTED,VAR_AMPERE_PRODUCTED,*current_produced);
	*power_factor=random_value_generation_gradual_variation(MIN_POWER_FACTOR,MAX_POWER_FACTOR,VAR_POWER_FACTOR,*power_factor);
	
	*instant_power=compute_total_instant_power(*voltage,*current_consumed,*current_produced,*power_factor);

}

/**
 * This function simulates the sudden shutdown of all values ​​due to the tripping of the circuit breaker once the MAX POWER has been reached.
 * @param current_consumed is the numeric value of the current consumed by the building
 * @param current_produced is the numeric value of the current produced by the building
 * @param power_factor is the numeric value of the loads attacched to the building 
 * @param instant_power is the numeric value of the overall power produced/consumed by the building
 * @param nr_seconds_passed_last_send is the numer of seconds passed since last sending power resource update message
 * @param last_instant_power_send is the numeric value of the last sending power resource update message
 * @param MAX_POWER_ALLOWED is the maximum power allowed to a building 
*/
void reset_sensor_values(float *current_consumed,float *current_produced,float *power_factor,float *instant_power,int *nr_seconds_passed_last_send,float *last_instant_power_send,float MAX_POWER_ALLOWED){
	*current_consumed=0;
	*current_produced=0;
	*power_factor=0;
	*instant_power=0;
	*nr_seconds_passed_last_send=0;
	*last_instant_power_send=-MAX_POWER_ALLOWED;
}


/**
 * This function aims to create a string representing the message for changing the state of an activation/disactivation of a building (remotely).
 * @param json_string_payload the string to be populated as json payload
 * @param state a boolean value indicating the new state to be changed
 */
void create_msg_registration(char **json_string_payload){
	
	char base_name[BASE_NAME_MAX_LEN];
	
	cJSON *root = cJSON_CreateObject();
	create_base_name_attribute(base_name);
	cJSON_AddStringToObject(root, "full_name", base_name);
	// For now this value is fixed
	cJSON_AddStringToObject(root, "alias", "house_1");
	
	cJSON_AddNumberToObject(root, "type", 1);
	
	char *json_payload=cJSON_PrintUnformatted(root);
	printf("%s\n",json_payload);
	
	// Make sure to allocate memory for the json_string_payload
	if (*json_string_payload == NULL) {
		*json_string_payload = (char *)malloc(strlen(json_payload) + 1);
		if (*json_string_payload == NULL) {
			printf("Memory allocation failed!\n");
			free(json_payload);
			cJSON_Delete(root); // Clean up the JSON object
			return;
		}
	}
	
	// Copy the formatted JSON string into the provided string buffer
	strcpy(*json_string_payload, json_payload);

	// Free the temporary JSON string
	free(json_payload);
	
	// Clean up the root object to avoid memory leaks
	cJSON_Delete(root);
}





