{
 "title": "Trends_Smart_Transformer_1",
 "description": "This dashboard monitors the trends of currents and voltage of the Smart Transformer_1",
 "time": { "from": "2024-09-26T10:59:28.000Z", "to": "2024-09-26T11:01:06.000Z" },
 "panels": [
  {
   "title": "Percentages of Faults",
   "type": "piechart",
   "description": "This bar chart emphasizes the percentage of faults that occur in the smart transformer during the time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "SPARK_IOT",
     "rawSql": "SELECT CONCAT(state,'') AS `STATE_CODE`, COUNT(state) AS `type_fault` FROM smart_transformer_sensor_measurments GROUP BY STATE_CODE ORDER BY STATE_CODE;"
    }
   ]
  },
  {
   "title": "Voltage Trends",
   "type": "timeseries",
   "description": "This describes the behavior of the voltages Va, Vb, Vc in the smart transformer over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "SPARK_IOT",
     "rawSql": "SELECT VA, VB, VC, TIMESTAMP FROM SPARK_IOT.smart_transformer_sensor_measurments LIMIT 50 "
    }
   ]
  },
  {
   "title": "Currents Trend",
   "type": "timeseries",
   "description": "This describes the behavior of the currents Ia, Ib, Ic in the smart transformer over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "SPARK_IOT",
     "rawSql": "SELECT IA, IB, IC, TIMESTAMP FROM SPARK_IOT.smart_transformer_sensor_measurments LIMIT 50 "
    }
   ]
  }
 ]
}