CREATE SCHEMA IF NOT EXISTS SPARK_IOT;

use SPARK_IOT;

CREATE TABLE IF NOT EXISTS iot_devices(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	FULL_NAME VARCHAR (30) UNIQUE NOT NULL,
	TYPE INT NOT NULL DEFAULT 1,
	ALIAS VARCHAR(30) NOT NULL,
	IP_ADDRESS VARCHAR(42) NOT NULL,
	STATUS boolean NOT NULL DEFAULT TRUE,
	MAX_POWER DECIMAL(7,2) NOT NULL DEFAULT 0
);

	
	
CREATE TABLE IF NOT EXISTS smart_power_meter_measurments(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	ID_DEVICE INT NOT NULL,
	POWER DECIMAL (7,2) NOT NULL DEFAULT 0,
	TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (ID_DEVICE) REFERENCES iot_devices(ID)
	);
	
	
CREATE TABLE IF NOT EXISTS smart_transformer_sensor_measurments(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	ID_DEVICE INT NOT NULL,
	STATE INT NOT NULL DEFAULT 0,
	IA DECIMAL (7,2) DEFAULT 0,
	IB DECIMAL (7,2) DEFAULT 0,
	IC DECIMAL (7,2) DEFAULT 0,
	
	VA DECIMAL (7,2) DEFAULT 0,
	VB DECIMAL (7,2) DEFAULT 0,
	VC DECIMAL (7,2) DEFAULT 0,
	TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (ID_DEVICE) REFERENCES iot_devices(ID)
);